package game;

public class GCEnum {
	public static final int CT_DUNGEON = 0;
	public static final int CT_GUILD = 1;
	public static final int CT_INDIGO = 2;
	public static final int CT_UNLIMITED = 3;
	public static final int CT_BEGINNER = 4;
	public static final int CT_ROOKIE = 5;
	public static final int CT_EXPERT = 6;
	public static final int CT_MASTER = 7;
	public static final int CT_SQUARE = 8;
	public static final int CT_GUILD_UNLIMITED = 9;
	public static final int CT_GUILD_MASTER = 10;
	public static final int CT_GUILD_EXPERT = 14;
	public static final int CT_GUILD_ROOKIE = 18;
	public static final int CT_GUILD_BEGINNER = 20;
	public static final int CT_AGIT = 21;
	public static final int CT_AUTOMATCH = 22;

	public static final int GC_GMC_MATCH = 0; //대전
	public static final int GC_GMC_GUILD_BATTLE = 1; //길드전
	public static final int GC_GMC_DUNGEON = 2; //퀘스트
	public static final int GC_GMC_INDIGO = 3; //용사의섬
	public static final int GC_GMC_TUTORIAL = 4; //튜토리얼
	public static final int GC_GMC_TAG_MATCH = 5; //태그매치
	public static final int GC_GMC_MONSTER_CRUSADER = 6; //몬스터원정대
	public static final int GC_GMC_MONSTER_HUNT = 7; //몬스터대전
	public static final int GC_GMC_DEATHMATCH = 8; //데스매치
	public static final int GC_GMC_MINIGAME = 9; //미니게임
	public static final int GC_GMC_ANGELS_EGG = 10; //천사의알
	public static final int GC_GMC_CAPTAIN = 11; //대장전
	public static final int GC_GMC_DOTA = 12; //점령전
	public static final int GC_GMC_AGIT = 13; //아지트
	public static final int GC_GMC_AUTOMATCH = 14; //자동매칭대전.
	public static final int GC_GMC_FATAL_DEATHMATCH = 15; //페이탈데스매치

	public static final int GC_GM_INVALID = -1; //invalidgamemodevalue
	public static final int GC_GM_TUTORIAL = 0; //튜토리얼
	public static final int GC_GM_TEAM_MODE = 1; //팀모드
	public static final int GC_GM_SURVIVAL_MODE = 2; //서바이벌모드
	public static final int GC_GM_TAG_TEAM = 3; //태그매치팀모드
	public static final int GC_GM_TAG_SURVIVAL = 4; //태그매치서바이벌
	public static final int GC_GM_GUILD_BATTLE = 5; //길드전모드
	public static final int GC_GM_INDIGO_TEAM = 6; //용사의섬
	public static final int GC_GM_QUEST0 = 7; //시련의숲
	public static final int GC_GM_QUEST1 = 8; //시련의탑
	public static final int GC_GM_QUEST2 = 9; //세르딘성외곽
	public static final int GC_GM_QUEST3 = 10; //캐리비치
	public static final int GC_GM_QUEST4 = 11; //오크사원
	public static final int GC_GM_QUEST5 = 12; //고르고스던전
	public static final int GC_GM_QUEST6 = 13; //엘프의숲
	public static final int GC_GM_QUEST7 = 14; //맹세의계곡
	public static final int GC_GM_QUEST8 = 15; //망각의늪
	public static final int GC_GM_QUEST9 = 16; //망자의묘지
	public static final int GC_GM_QUEST10 = 17; //잊혀진도시
	public static final int GC_GM_QUEST11 = 18; //가이코즈의성
	public static final int GC_GM_QUEST12 = 19; //파투세이의바다
	public static final int GC_GM_QUEST13 = 20; //엘리아대륙
	public static final int GC_GM_QUEST14 = 21; //불의사원
	public static final int GC_GM_QUEST15 = 22; //헬브릿지
	public static final int GC_GM_QUEST16 = 23; //카제아제의성
	public static final int GC_GM_QUEST17 = 24; //카스툴유적지하층
	public static final int GC_GM_QUEST18 = 25; //카스툴유적지상층
	public static final int GC_GM_QUEST19 = 26; //베르메시아의최후
	public static final int GC_GM_QUEST20 = 27; //제니아접경지
	public static final int GC_GM_MONSTER_CRUSADER = 28; //몬스터원정대
	public static final int GC_GM_MONSTER_HUNT = 29; //몬스터대전(시즌1.미사용)
	public static final int GC_GM_QUEST21 = 30; //순환의신전
	public static final int GC_GM_DEATH_TEAM = 31; //데스매치팀
	public static final int GC_GM_DEATH_SURVIVAL = 32; //데스매치서바이벌
	public static final int GC_GM_MINIGAME_TREEDROP = 33; //미니게임통나무떨어지기
	public static final int GC_GM_MINIGAME_BALLOON = 34; //미니게임풍선터뜨리기
	public static final int GC_GM_MINIGAME_BUTTERFRY = 35; //미니게임나비잡기
	public static final int GC_GM_QUEST22 = 36; //소실의협곡
	public static final int GC_GM_ANGELS_EGG = 37; //천사의알
	public static final int GC_GM_CAPTAIN = 38; //대장전
	public static final int GC_GM_QUEST23 = 39; //실버랜드성난엔트의숲
	public static final int GC_GM_QUEST24 = 40; //실버랜드실버나이츠
	public static final int GC_GM_QUEST25 = 41; //실버랜드미명의호수
	public static final int GC_GM_QUEST26 = 42; //제니아이그니스의산맥
	public static final int GC_GM_QUEST27 = 43; //싫버랜드수룡의늪
	public static final int GC_GM_QUEST28 = 44; //실버랜드원시의섬
	public static final int GC_GM_QUEST29 = 45; //실버랜드드레이크웜의영지
	public static final int GC_GM_QUEST30 = 46; //실버랜드빅터의요새
	public static final int GC_GM_QUEST31 = 47; //제니아조율의제단
	public static final int GC_GM_QUEST32 = 48; //제니아파괴의신전
	public static final int GC_GM_QUEST33 = 49; //제니아생명의숲
	public static final int GC_GM_QUEST34 = 50; //제니아지배의성
	public static final int GC_GM_QUEST35 = 51; //베르메시아보스던전
	public static final int GC_GM_QUEST36 = 52; //실버랜드보스던전
	public static final int GC_GM_QUEST37 = 53; //엘리아보스던전
	public static final int GC_GM_QUEST38 = 54; //제니아보스던전
	public static final int GC_GM_QUEST39 = 55; //고블린노역소
	public static final int GC_GM_QUEST40 = 56; //지하암흑터널
	public static final int GC_GM_QUEST41 = 57; //쿵지쿵지
	public static final int GC_GM_QUEST42 = 58; //드워프전초기지
	public static final int GC_GM_QUEST43 = 59; //신기루사막
	public static final int GC_GM_QUEST44 = 60; //드워프보급로
	public static final int GC_GM_QUEST45 = 61; //썬더해머
	public static final int GC_GM_QUEST46 = 62; //영웅던전(파멸의성소)
	public static final int GC_GM_QUEST47 = 63; //영웅던전(지옥의용광로)
	public static final int GC_GM_QUEST48 = 64; //고대왕국의흔적
	public static final int GC_GM_DOTA = 65; //점령전
	public static final int GC_GM_AGIT = 66; //아지트
	public static final int GC_GM_QUEST49 = 67; //이벤트던전카니발(악몽의서커스)
	public static final int GC_GM_QUEST50 = 68; //이벤트릴레이던전(앵그리보오스)
	public static final int GC_GM_QUEST51 = 69; //이벤트영웅던전(악몽의서커스리뉴얼)
	public static final int GC_GM_QUEST52 = 70; //릴레이영웅던전슈퍼몬스터(환영의미궁)
	public static final int GC_GM_QUEST53 = 71; //명계열차301(GhostTrain)
	public static final int GC_GM_QUEST54 = 72; //배고픈펫들의반란
	public static final int GC_GM_QUEST55 = 73; //카루엘접경지(KaruelBorder)
	public static final int GC_GM_QUEST56 = 74; //카루엘(Karuel)
	public static final int GC_GM_QUEST57 = 75; //이벤트던전(야시장)
	public static final int GC_GM_QUEST58 = 76; //레이드던전
	public static final int GC_GM_AUTOMATCH_TEAM = 77; //대전팀자동매칭
	public static final int GC_GM_QUEST59 = 78; //사막도적마을(아툼)
	public static final int GC_GM_QUEST60 = 79; //라협곡(아툼)
	public static final int GC_GM_QUEST61 = 80; //세트의피라미드(아툼)
	public static final int GC_GM_QUEST62 = 81; //코우나트붕괴지(아케메디아)
	public static final int GC_GM_QUEST63 = 82; //코우나트붕괴지(이벤트던전)
	public static final int GC_GM_QUEST64 = 83; //이벤트슈팅던전(탈린의역습)
	public static final int GC_GM_QUEST65 = 84; //아델신대륙(저주받은정원)
	public static final int GC_GM_QUEST66 = 85; //아델신대륙(오염된지하실)
	public static final int GC_GM_QUEST67 = 86; //아델신대륙(망령이깃든복도)
	public static final int GC_GM_QUEST68 = 87; //아델신대륙(배신자의화실)
	public static final int GC_GM_QUEST69 = 88; //아델신대륙(어둠에물든서재)
	public static final int GC_GM_QUEST70 = 89; //아델신대륙(아라크네의둥지)
	public static final int GC_GM_QUEST71 = 90; //베이가스신대륙(골리아스서식지)
	public static final int GC_GM_QUEST72 = 91; //베이가스신대륙(고대골렘의무덤)
	public static final int GC_GM_QUEST73 = 92; //베이가스신대륙(그림자밀림)
	public static final int GC_GM_QUEST74 = 93; //베이가스신대륙(라세르타의사냥터)
	public static final int GC_GM_QUEST75 = 94; //베이가스신대륙(절망의대지)
	public static final int GC_GM_QUEST76 = 95; //베이가스신대륙(차원의경계)
	public static final int GC_GM_FATAL_DEATH_TEAM = 96; //페이탈데스매치팀
	public static final int GC_GM_FATAL_DEATH_SURVIVAL = 97; //페이탈데스매치서바이벌
	public static final int GC_GM_QUEST77 = 98; //--엘리아사냥터
	public static final int GC_GM_QUEST78 = 99; //--제니아사냥터
	public static final int GC_GM_QUEST79 = 100; //--아툼사냥터
	public static final int GC_GM_QUEST80 = 101; //--아케메디아사냥터
	public static final int GC_GM_QUEST81 = 102; //--만렙컨트롤던전

	public static final int GC_GS_FOREST_OF_ELF = 0; // 엘프의 숲
	public static final int GC_GS_SWAMP_OF_OBLIVION = 1; // 망각의 늪
	public static final int GC_GS_FLYING_SHIP = 2; // 비공정
	public static final int GC_GS_VALLEY_OF_OATH = 3; // 맹세의 계곡
	public static final int GC_GS_FOGOTTEN_CITY = 4; // 잊혀진 도시
	public static final int GC_GS_BABEL_OF_X_MAS = 5; // X-마스의 바벨
	public static final int GC_GS_TEMPLE_OF_FIRE = 6; // 불의 사원
	public static final int GC_GS_SHOOTING_FIELD = 7; // 사격 대회장
	public static final int GC_GS_HELL_BRIDGE = 8; // 헬 브릿지
	public static final int GC_GS_TEMPLE_OF_ORC = 9; // 오크 사원
	public static final int GC_GS_GUILD = 10; // 길드맵(세르딘 성 외곽)
	public static final int GC_GS_CARRIBEACH = 11; // 캐리비치
	public static final int GC_GS_QUEST1_A = 12; // 퀘스트1 A맵
	public static final int GC_GS_QUEST1_B = 13; // 퀘스트1 B맵
	public static final int GC_GS_QUEST1_C = 14; // 퀘스트1 C맵
	public static final int GC_GS_QUEST1_D = 15; // 퀘스트1 D맵
	public static final int GC_GS_QUEST1_X_MAS = 16; // 퀘스트1 크리스마스 맵
	public static final int GC_GS_QUEST2_A = 17; // 퀘스트2 A맵
	public static final int GC_GS_QUEST2_B = 18; // 퀘스트2 B맵
	public static final int GC_GS_QUEST2_C = 19; // 퀘스트2 C맵
	public static final int GC_GS_QUEST2_D = 20; // 퀘스트2 D맵
	public static final int GC_GS_QUEST2_E = 21; // 퀘스트2 E맵
	public static final int GC_GS_QUEST3_A = 22; // 퀘스트3 A맵
	public static final int GC_GS_QUEST3_B = 23; // 퀘스트3 B맵
	public static final int GC_GS_QUEST3_C = 24; // 퀘스트3 C맵
	public static final int GC_GS_QUEST3_D = 25; // 퀘스트3 D맵
	public static final int GC_GS_QUEST3_E = 26; // 퀘스트3 E맵
	public static final int GC_GS_QUEST4_A = 27; // 퀘스트4 A맵
	public static final int GC_GS_QUEST4_B = 28; // 퀘스트4 B맵
	public static final int GC_GS_QUEST4_C = 29; // 퀘스트4 C맵
	public static final int GC_GS_QUEST4_D = 30; // 퀘스트4 D맵
	public static final int GC_GS_QUEST4_E = 31; // 퀘스트4 E맵
	public static final int GC_GS_QUEST4_F = 32; // 퀘스트4 E맵
	public static final int GC_GS_QUEST6_A = 33; // 퀘스트 FINAL A맵
	public static final int GC_GS_QUEST6_B = 34; // 퀘스트 FINAL B맵
	public static final int GC_GS_QUEST6_C = 35; // 퀘스트 FINAL C맵
	public static final int GC_GS_QUEST6_D = 36; // 퀘스트 FINAL D맵
	public static final int GC_GS_QUEST6_E = 37; // 퀘스트 FINAL E맵
	public static final int GC_GS_QUEST6_F = 38; // 퀘스트 FINAL F맵
	public static final int GC_GS_QUEST6_G = 39; // 퀘스트 FINAL G맵
	public static final int GC_GS_QUEST_ZERO_A = 40;
	public static final int GC_GS_QUEST_ZERO_B = 41;
	public static final int GC_GS_QUEST_ZERO_C = 42;
	public static final int GC_GS_FOREST_OF_TRIAL = 43;
	public static final int GC_GS_QUEST_ZERO_2_A = 44;
	public static final int GC_GS_QUEST_ZERO_2_B = 45;
	public static final int GC_GS_QUEST_ZERO_2_C = 46;
	public static final int GC_GS_GRAVEYARD_OF_DECEASED = 47; // 망자의 묘지
	public static final int GC_GS_CASTUL_TEMPLE_A = 48; //카스툴 유적지 상층
	public static final int GC_GS_CASTUL_TEMPLE_B = 49;
	public static final int GC_GS_CASTUL_TEMPLE_C = 50;
	public static final int GC_GS_CASTUL_TEMPLE_D = 51;
	public static final int GC_GS_CASTUL_TEMPLE_UNDER_A = 52; // 카스툴 유적지 하층
	public static final int GC_GS_CASTUL_TEMPLE_UNDER_B = 53;
	public static final int GC_GS_CASTUL_TEMPLE_UNDER_C = 54;
	public static final int GC_GS_CASTUL_TEMPLE_UNDER_D = 55;
	public static final int GC_GS_CASTUL_TEMPLE_UNDER_E = 56;
	public static final int GC_GS_CASTUL_TEMPLE_UNDER_F = 57;
	public static final int GC_GS_CASTUL_TEMPLE_UNDER_G = 58;
	public static final int GC_GS_CASTUL_TEMPLE_UNDER_H = 59;
	public static final int GC_GS_CASTUL_TEMPLE_UNDER_I = 60;
	public static final int GC_GS_CASTUL_TEMPLE_UNDER_J = 61;
	public static final int GC_GS_CASTUL_TEMPLE_UNDER_K = 62;
	public static final int GC_GS_CASTUL_TEMPLE_UNDER_L = 63;
	public static final int GC_GS_BERMESIA_FINAL_A = 64; // 베르메시아 최후 A맵 s1
	public static final int GC_GS_BERMESIA_FINAL_B = 65; // 베르메시아 최후 B맵 s2
	public static final int GC_GS_BERMESIA_FINAL_C = 66; // 베르메시아 최후 C맵 s3
	public static final int GC_GS_BERMESIA_FINAL_D = 67; // 베르메시아 최후 D맵 s4
	public static final int GC_GS_BERMESIA_FINAL_E = 68; // 베르메시아 최후 E맵 s5
	public static final int GC_GS_BERMESIA_FINAL_F = 69; // 베르메시아 최후 F맵 s6
	public static final int GC_GS_BERMESIA_FINAL_G = 70; // 베르메시아 최후 G맵 s7
	public static final int GC_GS_BERMESIA_FINAL_H = 71; // 베르메시아 최후 H맵 s8
	public static final int GC_GS_BERMESIA_FINAL_I = 72; // 베르메시아 최후 I맵 s9
	public static final int GC_GS_BERMESIA_FINAL_J = 73; // 베르메시아 최후 J맵 s10
	public static final int GC_GS_BERMESIA_FINAL_K = 74; // 베르메시아 최후 K맵 s11
	public static final int GC_GS_BERMESIA_FINAL_L = 75; // 베르메시아 최후 L맵 s12
	public static final int GC_GS_BERMESIA_FINAL_M = 76; // 베르메시아 최후 M맵 s13
	public static final int GC_GS_BERMESIA_FINAL_N = 77; // 베르메시아 최후 N맵 s14
	public static final int GC_GS_BERMESIA_FINAL_O = 78; // 베르메시아 최후 O맵 s15
	public static final int GC_GS_BERMESIA_FINAL_P = 79; // 베르메시아 최후 P맵 s16
	public static final int GC_GS_GOD_ISLAND1_A = 80;
	public static final int GC_GS_GOD_ISLAND1_B = 81;
	public static final int GC_GS_GOD_ISLAND1_C = 82;
	public static final int GC_GS_GOD_ISLAND1_D = 83;
	public static final int GC_GS_GOD_ISLAND1_E = 84;
	public static final int GC_GS_GOD_ISLAND1_F = 85;
	public static final int GC_GS_GOD_ISLAND1_G = 86;
	public static final int GC_GS_GOD_ISLAND1_H = 87;
	public static final int GC_GS_GOD_ISLAND1_I = 88;
	public static final int GC_GS_GOD_ISLAND1_J = 89;
	public static final int GC_GS_GOD_ISLAND1_K = 90;
	public static final int GC_GS_GOD_ISLAND1_L = 91;
	public static final int GC_GS_GOD_ISLAND1_M = 92;
	public static final int GC_GS_CASTUL_TEMPLE_E = 93;
	public static final int GC_GS_CASTUL_TEMPLE_F = 94;
	public static final int GC_GS_BAHIA = 95;
	public static final int GC_GS_AMAZON_FOREST = 96;
	public static final int GC_GS_MARKET_WATER = 97;
	public static final int GC_GS_RIZAL_PARK = 98;
	public static final int GC_GS_FOREST_OF_ELF_REVERS = 99; // 엘프의 숲 반전
	public static final int GC_GS_VALLEY_OF_OATH_REVERS = 100; // 맹세의 계곡 반전
	public static final int GC_GS_CASTLE_OF_RULE = 101; //지배의 성 (브라질 유저가 만든 맵)
}
